server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/app_chat"
    driverClassName: "com.mysql.cj.jdbc.Driver"  # Đây là dòng quan trọng
    username: root   # Mặc định username là root
    password: root   # Mặc định password là root


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
